### Pegar todos os estudantes
GET http://localhost:3003/estudantes

### Mudar um estudante de turma

PUT http://localhost:3003/estudantes
Content-Type: application/json

{
    "id": "rCmvIk",
    "turma_id":"gBVbMV"
}

### Criar um estudante

POST  http://localhost:3003/estudantes
Content-Type: application/json

{
    "nome": "Jose2",
    "email": "josey2@email.com",
    "data_nasc": "20/06/2003",
    "hobbys": ["teste1","teste2","teste3"]
}

### Buscar estudante pelo nome

GET http://localhost:3003/estudantes/search?term=adeir



### Pegar todos os docentes

GET http://localhost:3003/docentes
Content-Type: application/json


### Criar docentes
POST http://localhost:3003/docentes
Content-Type: application/json

{  
    "nome": "janayla",
    "email": "jana@labenu.com",
    "data_nasc": "18/10/2022",
    "especialidades": ["js","css","react"]

}

### Trocar o docente de turma
PUT http://localhost:3003/docentes
Content-Type: application/json

{
    "id":"Go3mksbdSBn",
    "turma_id":"tANmNw"
}

### Criar turma
POST http://localhost:3003/turma
Content-Type: application/json

{
    "nome":"shaw",
    "modulo": 1
}

### Pegar todas as turmas
GET http://localhost:3003/turma

### pegar turmas ativas
GET http://localhost:3003/turma/active


### Trocar modulo da turma
PUT http://localhost:3003/turma
Content-Type: application/json

{
    "id":"tANmNw",
    "modulo":1

}

### Pegar estudantes e professores da mesma turma
Get http://localhost:3003/turma/data/K2dRx6



