GET http://localhost:3003/estudantes

###

POST  http://localhost:3003/estudantes
Content-Type: application/json

{
    "id": "",
    "nome": "",
    "email": "",
    "data_nasc": "",
    "turma_id": "",
    "hobbys": ["codar"]
}

###

GET http://localhost:3003/estudantes/search?term=adeir


###

GET http://localhost:3003/docentes
Content-Type: application/json


###
POST http://localhost:3003/docentes
Content-Type: application/json

{  
    "nome": "Diego",
    "email": "dgo.eduardo@email.com",
    "data_nasc": "1990/04/20",
    "turma_id": "oy7Rca",
    "especialidades": ["React"]

}

###
PUT http://localhost:3003/docentes
Content-Type: application/json

{
    "id":"hqi6ElTJIKK",
    "turma_id":"IvxF2P"
}
