GET http://localhost:3003/estudantes

###

POST  http://localhost:3003/estudantes
Content-Type: application/json

{
    "id": "",
    "nome": "",
    "email": "",
    "data_nasc": "",
    "turma_id": "",
    "hobbys": ["codar"]
}

###

GET http://localhost:3003/estudantes/search?term=adeir

###
POST http://localhost:3003/turma
Content-Type: application/json

{
    "nome":"jumanji",
    "modulo": 0
}

###
GET http://localhost:3003/turma

###
GET http://localhost:3003/turma/active